name: ozi-release
description: "OZI release draft action."
inputs:
  python-dist:
    description: "python dist version string e.g. pyXY"
    required: true
  github-token:
    description: "GitHub workflow-generated token"
    required: true
  tag:
    description: "release tag name"
    required: true
outputs:
  hashes:
    description: "release file hashes for provenance"
    value: ${{ steps.hash.outputs.hashes }}
runs:
  using: "composite"
  steps:

  - uses: actions/download-artifact@v4
    name: ${{ inputs.python-dist }}

  - name: Move artifact
    run: cp -a ${{ inputs.python-dist }}/. ./
    shell: bash

  - name: Set up Python 3.10
    if: inputs.python-dist == 'py310'
    uses: actions/setup-python@v5
    with:
      cache: 'pip'
      python-version: '3.10'

  - name: Set up Python 3.11
    if: inputs.python-dist == 'py311'
    uses: actions/setup-python@v5
    with:
      cache: 'pip'
      python-version: '3.11'

  - name: Set up Python 3.12 
    if: inputs.python-dist == 'py312'
    uses: actions/setup-python@v5
    with:
      cache: 'pip'
      python-version: '3.12'

  - name: Install ${{ inputs.python-dist }} build dependencies
    run: |
        python -m pip install --upgrade pip
        python -m pip install --user --upgrade build
        python -m pip install --user --upgrade meson
        python -m pip install --user --upgrade OZI.build
        python -m pip install --user --upgrade setuptools_scm
        python -m pip install --user --upgrade ninja
        python -m pip install --user --upgrade pip-tools
    shell: bash

  - name: Configure git repository
    if: inputs.python-dist == 'py310'
    run: |
        git config --global user.email "noreply@oziproject.dev"
        git config --global user.name "OZI Packaging"
        rm -rf .git/COMMIT_EDITMSG
    shell: bash

  - name: Build wheel
    if: inputs.python-dist != 'py312'
    id: wheel
    run: |
      python -m build -w
    shell: bash

  - name: Build wheel and sdist
    if: inputs.python-dist == 'py312'
    id: sdist
    run: |
      python -m build
    shell: bash

  - uses: sigstore/gh-action-sigstore-python@v2.1.1
    if: inputs.python-dist == 'py312'
    with:
      inputs: dist/${{ github.event.repository.name }}-${{ inputs.tag }}.tar.gz
      release-signing-artifacts: true
      upload-signing-artifacts: true

  - uses: sigstore/gh-action-sigstore-python@v2.1.1
    if: inputs.python-dist == 'py312'
    with:
      inputs: dist/${{ github.event.repository.name }}-${{ inputs.tag }}-*.whl
      upload-signing-artifacts: true

  - name: Move wheel signing files
    if: inputs.python-dist == 'py312'
    run: |
      mkdir sig
      mv dist/*.whl.sigstore sig
    shell: bash

  - name: Move sdist signing file
    if: inputs.python-dist == 'py312'
    run: |
      mv dist/${{ github.event.repository.name }}-${{ inputs.tag }}.tar.gz.sigstore sig/${{ github.event.repository.name }}-${{ inputs.tag }}.tar.gz.sigstore
    shell: bash

  - name: Generate hashes for provenance
    shell: bash
    id: hash
    if: inputs.python-dist == 'py312'
    run: |
      # sha256sum generates sha256 hash for all artifacts.
      # base64 -w0 encodes to base64 and outputs on a single line.
      # sha256sum artifact1 artifact2 ... | base64 -w0
      echo "hashes=$(sha256sum ./dist/* | base64 -w0)" >> $GITHUB_OUTPUT

  - uses: actions/upload-artifact@v4.3.0
    if: inputs.python-dist == 'py310'
    with:
      name: 'py311'
      path: |
        !build/
        ./

  - uses: actions/upload-artifact@v4.3.0
    if: inputs.python-dist == 'py311'
    with:
      name: 'py312'
      path: |
        !py311/
        !build/
        ./

  - uses: actions/upload-artifact@v4.3.0
    if: inputs.python-dist == 'py312'
    with:
      path: |
        !py312/
        !build/
        ./
