name: ozi-release
description: "OZI release draft action."
inputs:
  python-dist:
    description: "python dist version string e.g. pyXY"
    required: true
  github-token:
    description: "GitHub workflow-generated token"
    required: true
outputs:
  drafted:
    description: "a release has been drafted"
    value: ${{ steps.draft.outputs.created }}
  hashes:
    description: "release file hashes for provenance"
    value: ${{ steps.hash.outputs.hashes }}
  tag:
    description: "release tag name"
    value: ${{ steps.version.outputs.tag }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4.1.1
    if: inputs.python-dist == 'py310'
    with:
      token: ${{ inputs.github-token }}
      fetch-depth: 0

  - name: Python Semantic Release
    id: release
    if: inputs.python-dist == 'py310'
    uses: python-semantic-release/python-semantic-release@v9.3.1
    with:
      github_token: ${{ inputs.github-token }}

  - name: Pass release draft status to job
    id: draft
    env:
      check: ${{ steps.release.outputs.released == 'true' || inputs.python-dist != 'py310' }}
    run: echo "created=${{ env.check }}" >> $GITHUB_OUTPUT
    shell: bash

  - uses: actions/download-artifact@v4
    if: steps.draft.outputs.created == 'true' && inputs.python-dist != 'py310'
    name: ${{ inputs.python-dist }}

  - name: Move artifact
    if: steps.draft.outputs.created == 'true' && inputs.python-dist != 'py310'
    run: cp -a ${{ inputs.python-dist }}/. ./
    shell: bash

  - name: Set version
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    id: version
    run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
    shell: bash

  - name: Set up Python 3.10
    if: inputs.python-dist == 'py310'
    uses: actions/setup-python@v5
    with:
      cache: 'pip'
      python-version: '3.10'

  - name: Set up Python 3.11
    if: inputs.python-dist == 'py311'
    uses: actions/setup-python@v5
    with:
      cache: 'pip'
      python-version: '3.11'

  - name: Set up Python 3.12 
    if: inputs.python-dist == 'py312'
    uses: actions/setup-python@v5
    with:
      cache: 'pip'
      python-version: '3.12'

  - name: Install ${{ inputs.python-dist }} build dependencies
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    run: |
        python -m pip install --upgrade pip
        python -m pip install --user --upgrade build
        python -m pip install --user --upgrade pyc_wheel
        python -m pip install --user --upgrade meson
        python -m pip install --user --upgrade mesonpep517
        python -m pip install --user --upgrade setuptools_scm
        python -m pip install --user --upgrade ninja
        python -m pip install --user --upgrade pip-tools
    shell: bash

  - name: Configure git repository
    if: inputs.python-dist == 'py310'
    run: |
        git config --global user.email "noreply@oziproject.dev"
        git config --global user.name "OZI Packaging"
        rm -rf .git/COMMIT_EDITMSG
        mkdir sig
    shell: bash

  - name: Build wheel
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    id: wheel
    run: |
      meson setup build
      python -m build -w
      python -m pyc_wheel dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}-py3-none-any.whl
      mv dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}-py3-none-any.whl dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}-${{ inputs.python-dist }}-none-any.whl
    shell: bash

  - name: Build sdist
    id: sdist
    if: inputs.python-dist== 'py312'
    run: |
      meson setup build --reconfigure
      pip install dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}-${{ inputs.python-dist }}-none-any.whl
      meson dist -C build --formats gztar --no-tests
      mv build/meson-dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}.tar.gz dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}.tar.gz 
    shell: bash

  - uses: sigstore/gh-action-sigstore-python@v2.1.1
    if: inputs.python-dist == 'py312'
    with:
      inputs: dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}.tar.gz
      release-signing-artifacts: true
      upload-signing-artifacts: true

  - uses: sigstore/gh-action-sigstore-python@v2.1.1
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    with:
      inputs: dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}-${{ inputs.python-dist }}-none-any.whl
      upload-signing-artifacts: true

  - name: Move wheel signing file
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    run: |
      mv dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}-${{ inputs.python-dist }}-none-any.whl.sigstore sig/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}-${{ inputs.python-dist }}-none-any.whl.sigstore
    shell: bash

  - name: Move sdist signing file
    if: inputs.python-dist == 'py312'
    run: |
      mv dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}.tar.gz.sigstore sig/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}.tar.gz.sigstore
    shell: bash

  - name: Remove dist-info file
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    run: |
      rm -r dist/${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}.dist-info
    shell: bash

  - name: Generate hashes for provenance
    shell: bash
    id: hash
    if: inputs.python-dist == 'py312'
    run: |
      # sha256sum generates sha256 hash for all artifacts.
      # base64 -w0 encodes to base64 and outputs on a single line.
      # sha256sum artifact1 artifact2 ... | base64 -w0
      echo "hashes=$(sha256sum ./dist/* | base64 -w0)" >> $GITHUB_OUTPUT

  - uses: actions/upload-artifact@v4.3.0
    if: inputs.python-dist == 'py310' && (steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true')
    with:
      name: 'py311'
      path: |
        !build/
        ./

  - uses: actions/upload-artifact@v4.3.0
    if: inputs.python-dist == 'py311' && (steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true')
    with:
      name: 'py312'
      path: |
        !py311/
        !build/
        ./

  - uses: actions/upload-artifact@v4.3.0
    if: inputs.python-dist == 'py312' && (steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true')
    with:
      path: |
        !py312/
        !build/
        ./
